// Errores
export const GET_ERRORS = 'GET_ERRORS'
// Usuario
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
// Proyectos
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS'
// API URL
export const GET_API_URL = 'GET_API_URL'
// Cargador de archivos
export const GET_FILES_TO_UPLOAD = 'GET_FILES_TO_UPLOAD'
export const ADD_FILE_TO_UPLOAD = 'ADD_FILE_TO_UPLOAD'
export const SET_FILE_STATUS = 'SET_FILE_STATUS'
export const CLEAN_FILES_TO_UPLOAD = 'CLEAN_FILES_TO_UPLOAD'
export const UPLOAD_FILE = 'UPLOAD_FILE'
export const SET_LOADER_STATUS = 'SET_LOADER_STATUS'
// VTP
export const SET_VTP_REQUEST_STATUS = 'SET_VTP_REQUEST_STATUS'
export const REQUEST_VTP_REPORTS = 'REQUEST_VTP_REPORTS'
export const UPDATE_VTP_REPORTS = 'UPDATE_VTP_REPORTS'

